[User]
username="tucker"
name="Tucker"

[System]
amd_cpu=true
swap_gpu_address=""
time_zone="America/Los_Angeles"

[Host]
hostname="homelab"
bind_gpu_by_default=true

[SSH]
enable_remote_access=true
public_keys=""

[Git]
name="Tucker"
email="public.tuckersn@gmail.com"
